### ISSUE TITLE
nrepl completion handler:  No namespace: null found

### ISSUE THREAD

**Issue by benjamin-asdf** [babashka/nbb#190]
```[benj@benj-pc nbb] 130 $ node lib/nbb_main.js nrepl-server 
nREPL server started on port 41433 on host 127.0.0.1 - nrepl://127.0.0.1:41433
cljs$core$ExceptionInfo [Error]: No namespace: null found
    at new cljs$core$ExceptionInfo (file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/cljs.core.js:36992:10)
    at Function.cljs$core$IFn$_invoke$arity$3 (file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/cljs.core.js:37053:9)
    at file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/sci.impl.utils.js:147:26
    at Function.cljs$core$IFn$_invoke$arity$4 (file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/sci.impl.utils.js:148:3)
    at file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/sci.impl.analyzer.js:6249:53
    at Object.sci$impl$types$eval [as eval] (file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/sci.impl.types.js:525:131)
    at Object.sci$impl$interpreter$eval_form [as eval_form] (file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/sci.impl.interpreter.js:35:27)
    at Object.sci$impl$interpreter$eval_string_STAR_ [as eval_string_STAR_] (file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/sci.impl.interpreter.js:73:36)
    at Object.sci$core$eval_string_STAR_ [as eval_string_STAR_] (file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/sci.core.js:354:29)
    at file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/nbb.impl.repl_utils.js:148:21 {
  data: {
    meta: null,
    cnt: 6,
    arr: [
      [Object],
      [Object],
      [Object],
      1,
      [Object],
      1,
      [Object],
      'No namespace: null found',
      [Object],
      [Object],
      [Object],
      null
    ],
    __hash: null,
    'cljs$lang$protocol_mask$partition0$': 16647951,
    'cljs$lang$protocol_mask$partition1$': 139268
  },
  cause: Error: No namespace: null found
      at Object.sci$impl$namespaces$sci_the_ns [as sci_the_ns] (file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/sci.impl.namespaces.js:1534:8)
      at sci$impl$namespaces$sci_ns_publics (file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/sci.impl.namespaces.js:1557:38)
      at Object.cljs$core$IFn$_invoke$arity$2 (file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/sci.impl.vars.js:1073:117)
      at file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/sci.impl.analyzer.js:5695:45
      at Object.sci$impl$types$eval [as eval] (file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/sci.impl.types.js:525:131)
      at file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/sci.impl.analyzer.js:6244:35
      at Object.sci$impl$types$eval [as eval] (file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/sci.impl.types.js:525:131)
      at Object.sci$impl$interpreter$eval_form [as eval_form] (file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/sci.impl.interpreter.js:35:27)
      at Object.sci$impl$interpreter$eval_string_STAR_ [as eval_string_STAR_] (file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/sci.impl.interpreter.js:73:36)
      at Object.sci$core$eval_string_STAR_ [as eval_string_STAR_] (file:///home/benj/repos/clojure/nbb/lib/cljs-runtime/sci.core.js:354:29),
  description: undefined,
  number: undefined,
  fileName: undefined,
  lineNumber: undefined,
  columnNumber: undefined
}
```
1) bb dev on 0060c6a41db1d913bf99e48a84a6f1d9779e0785
2) start nrepl server
3) send completion request
there is an error 

I am testing this by connecting with cider and evaling this form: 
```clojure 
(cider-nrepl-send-sync-request
 '("op" "complete"
   "prefix"
   "laod-"
   "ns" "example")
 (cider-current-connection))```

**Comment by benjamin-asdf** [comment]
I can also repro this on latest master via: 
```[benj@benj-pc nbb] 1 $ bb --main nbb-nrepl-tests

Testing nbb-nrepl-tests
nREPL server started on port 13337 on host 127.0.0.1 - nrepl://127.0.0.1:13337

ERROR in (pprint-test) (/home/benj/repos/clojure/nbb/script/nbb_nrepl_tests.clj:)
Uncaught exception, not in assertion.
```
