### ISSUE TITLE
Unable to use built in reagent.core ns when building the output of `nbb bundle` with `ncc`

### ISSUE THREAD

**Issue by evanlouie** [babashka/nbb#233]
**version**: `nbb v0.6.122`

**platform** macOS 12.4 / Node v18.4.0

**problem**:

- Bundling a script with `nbb bundle` that utilizes the `reagent.core` namespace will output some errors to standard out (see the repro below).
- The `nbb bundle` command doesn't fail and the output is usable via `node out.mjs`
- Bundling `out.mjs` with `ncc build out.mjs` will create a `dist/index.mjs` file which throws an error and is unusable (see repro below).

**repro**:

package.json

```json
{
  "type": "module",
  "scripts": {
    "build": "rm -rf dist && nbb bundle foo.cljs -o out.mjs && ncc build out.mjs"
  },
  "devDependencies": {
    "nbb": "^0.6.122",
    "ncc": "^0.3.6"
  },
  "dependencies": {
    "ink": "^3.2.0"
  }
}
```

foo.cljs:

```clj
(ns foo
  (:require
    [cljs.pprint :as pprint]
    ["ink" :refer [render Text]]
    [reagent.core :as r]))

(defonce state (r/atom 0))

(doseq [n (range 1 11)]
  (js/setTimeout #(swap! state inc) (* n 500)))

(defn hello []
  [:> Text {:color "green"} "Hello, world! " @state])

(render (r/as-element [hello]))
```

Running the build command:

```sh
npm run build

> build
> rm -rf dist && nbb bundle foo.cljs -o out.mjs && ncc build out.mjs

Error: ENOENT: no such file or directory, open 'reagent/core.cljs'
    at Object.openSync (node:fs:599:3)
    at Module.readFileSync (node:fs:467:35)
    at file:///Users/evlouie/workspace/tmp/nbb-test/node_modules/nbb/lib/nbb_bundler.js:12:12
    at file:///Users/evlouie/workspace/tmp/nbb-test/node_modules/nbb/lib/nbb_core.js:407:296
    at mca (file:///Users/evlouie/workspace/tmp/nbb-test/node_modules/nbb/lib/nbb_core.js:407:309)
    at Gs.l (file:///Users/evlouie/workspace/tmp/nbb-test/node_modules/nbb/lib/nbb_core.js:1719:321)
    at Gs.A (file:///Users/evlouie/workspace/tmp/nbb-test/node_modules/nbb/lib/nbb_core.js:1719:449)
    at $APP.Zg.D (file:///Users/evlouie/workspace/tmp/nbb-test/node_modules/nbb/lib/nbb_core.js:974:383)
    at Hs (file:///Users/evlouie/workspace/tmp/nbb-test/node_modules/nbb/lib/nbb_core.js:411:436)
    at fu.l (file:///Users/evlouie/workspace/tmp/nbb-test/node_modules/nbb/lib/nbb_core.js:1720:205) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'reagent/core.cljs'
}
[babashka] Ignoring read error while assembling uberscript near 5:27
ncc: Version 0.34.0
ncc: Compiling file index.mjs into ESM
3937kB  dist/index.mjs
3937kB  [4283ms] - ncc 0.34.0
```

calling the final bundle:

```sh
node dist/index.mjs
file:///Users/evlouie/workspace/tmp/nbb-test/dist/index.mjs:68137
        throw ex;
        ^

ReferenceError: _a is not defined
    at file:///Users/evlouie/workspace/tmp/nbb-test/dist/index.mjs:69230:65
    at file:///Users/evlouie/workspace/tmp/nbb-test/dist/index.mjs:69674:5
    at 8648 (file:///Users/evlouie/workspace/tmp/nbb-test/dist/index.mjs:78048:1)
    at __nccwpck_require__ (file:///Users/evlouie/workspace/tmp/nbb-test/dist/index.mjs:80981:42)
    at 4056 (file:///Users/evlouie/workspace/tmp/nbb-test/dist/index.mjs:4224:48)
    at __nccwpck_require__ (file:///Users/evlouie/workspace/tmp/nbb-test/dist/index.mjs:80981:42)
    at 5281 (file:///Users/evlouie/workspace/tmp/nbb-test/dist/index.mjs:3832:38)
    at __nccwpck_require__ (file:///Users/evlouie/workspace/tmp/nbb-test/dist/index.mjs:80981:42)
    at 9669 (file:///Users/evlouie/workspace/tmp/nbb-test/dist/index.mjs:4539:31)
    at __nccwpck_require__ (file:///Users/evlouie/workspace/tmp/nbb-test/dist/index.mjs:80981:42)

Node.js v18.4.0
```

**expected behavior**

- Should be able to utilize the built in `reagent.core` namespace in JS files made from `nbb bundle` -> `ncc build`

**Comment by borkdude** [comment]
It seems ink and ncc have a problem with each other. Repro:

out.mjs:
```
import * as ink from 'ink'
```

ncc build out.mjs 
node dist/index.mjs
```

```
ReferenceError: _a is not defined
```

**Comment by borkdude** [comment]
Should work now with 0.6.123 (being published as I write this) and webpack. See the bundle docs for an example.
