### ISSUE TITLE
couldn't find 'java' when using `nbb` in a docker container

### ISSUE THREAD

**Issue by samm81** [babashka/nbb#347]
## version

```
$ bb --version
babashka v1.3.189
$ npx nbb --version
nbb v1.2.182
```

tried a couple of different docker base images, including `node:18-slim` `node:18-alpine` `babashka/babashka:1.3.189-alpine`

always on node 18

## problem

I'm probably just misunderstanding something. new to the ecosystem.

I can get `bb` working ok using the install script. `npx nbb` runs find so long as there is no `nbb.edn` file. but when I add an `nbb.edn` file with a dependency I get

```
Exception in thread "main" java.lang.Exception: Couldn't find 'java'. Please set JAVA_HOME.
```

(full error at bottom in appendix)

as I understood it `babashka` (& therefore `nbb`) is described as "grab the self-contained binary and run. No JVM needed." so why is it asking for a `JAVA_HOME` ?

my `nbb.edn` file:

```edn
{:deps
 {logseq/graph-parser
  {:git/url "https://github.com/logseq/logseq"
   :git/sha "1ff9f7a1b2a261ca93fa83c217bf0c679ff404d3"
   :git/tag "0.10.7"
   :deps/root "deps/graph-parser"}}}
```

## repro

my `Dockerfile`:

```Dockerfile
FROM node:18-slim

RUN apt-get update \
  && apt-get install --yes --no-install-recommends bash curl ca-certificates \
  git

WORKDIR /app

RUN curl -s https://raw.githubusercontent.com/babashka/babashka/master/install | bash

COPY package.json package-lock.json ./

RUN npm install

COPY nbb.edn ./

ENTRYPOINT ["bash"]
```

`package.json`

```json
{
  "dependencies": {
    "@logseq/nbb-logseq": "^1.2.173",
    "chokidar": "^3.6.0",
    "express": "^4.18.3",
    "mldoc": "^1.5.8"
  }
}
```

```bash
$ docker build . -t nbb
$ docker run -it --rm nbb
root@ad065ae17806:/app# npx nbb
Need to install the following packages:
nbb@1.2.182
Ok to proceed? (y) y
Downloading dependencies...
Exception in thread "main" java.lang.Exception: Couldn't find 'java'. Please set JAVA_HOME.
        at borkdude.deps$get_java_cmd.invokeStatic(deps.clj:281)
...
```

## expected behavior

since `babashka` (& therefore `nbb`) is meant to run with the java runtime, then I shouldn't be asked for a `JAVA_HOME` ? is my understanding ?

## appendix

full `npx nbb` error:

```
root@51932603d27a:/app# npx nbb
Downloading dependencies...
Exception in thread "main" java.lang.Exception: Couldn't find 'java'. Please set JAVA_HOME.
        at borkdude.deps$get_java_cmd.invokeStatic(deps.clj:281)
        at borkdude.deps$_main.invokeStatic(deps.clj:902)
        at borkdude.deps$_main.doInvoke(deps.clj:882)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at babashka.impl.deps$add_deps$fn__27345$fn__27346.invoke(deps.clj:113)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at babashka.impl.deps$add_deps$fn__27345.invoke(deps.clj:113)
        at babashka.impl.deps$add_deps.invokeStatic(deps.clj:113)
        at babashka.main$exec$fn__32212.invoke(main.clj:872)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at babashka.main$exec.invokeStatic(main.clj:824)
        at babashka.main$main.invokeStatic(main.clj:1201)
        at babashka.main$main.doInvoke(main.clj:1148)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at babashka.main$_main$f__32337__auto____32347.invoke(main.clj:1240)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
Exception in thread "main" java.lang.NullPointerException
        at clojure.lang.RT.intCast(RT.java:1221)
        at babashka.main$_main.invokeStatic(main.clj:1240)
        at babashka.main$_main.doInvoke(main.clj:1226)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at babashka.main.main(Unknown Source)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Command failed: bb --config /app/.nbb/.cache/28933b543a6711cd9a5b1de35df7de63f96025b0/deps.edn --deps-root /app uberjar /app/.nbb/.cache/28933b543a6711cd9a5b1de35df7de63f96025b0/nbb-deps.jar
Exception in thread "main" java.lang.Exception: Couldn't find 'java'. Please set JAVA_HOME.
        at borkdude.deps$get_java_cmd.invokeStatic(deps.clj:281)
        at borkdude.deps$_main.invokeStatic(deps.clj:902)
        at borkdude.deps$_main.doInvoke(deps.clj:882)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at babashka.impl.deps$add_deps$fn__27345$fn__27346.invoke(deps.clj:113)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at babashka.impl.deps$add_deps$fn__27345.invoke(deps.clj:113)
        at babashka.impl.deps$add_deps.invokeStatic(deps.clj:113)
        at babashka.main$exec$fn__32212.invoke(main.clj:872)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at babashka.main$exec.invokeStatic(main.clj:824)
        at babashka.main$main.invokeStatic(main.clj:1201)
        at babashka.main$main.doInvoke(main.clj:1148)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at babashka.main$_main$f__32337__auto____32347.invoke(main.clj:1240)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
Exception in thread "main" java.lang.NullPointerException
        at clojure.lang.RT.intCast(RT.java:1221)
        at babashka.main$_main.invokeStatic(main.clj:1240)
        at babashka.main$_main.doInvoke(main.clj:1226)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at babashka.main.main(Unknown Source)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

**Comment by borkdude** [comment]
The Clojure ecosystem uses tools.deps to resolve dependencies and that is written in Java.

In Docker you could for example download GraalVM: https://www.graalvm.org/downloads/
and set `JAVA_HOME` to the downloaded JVM.

**Comment by samm81** [comment]
wow, fastest response I've ever had !

thank you for explaining :)

I got it working now :D - for anyone else who stumbles into this note that the graalvm binary won't run on alpine. so my final `Dockerfile`

```Dockerfile
FROM node:18-slim

RUN apt-get update \
  && apt-get install --yes --no-install-recommends curl ca-certificates wget \
  && apt-get install --yes --no-install-recommends git \
  && apt-get install --yes --no-install-recommends bash

WORKDIR /app

RUN curl -s https://raw.githubusercontent.com/babashka/babashka/master/install | bash

RUN cd / \
  && wget https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_linux-x64_bin.tar.gz \
  && tar xzvf graalvm-jdk-21_linux-x64_bin.tar.gz
ENV JAVA_HOME=/graalvm-jdk-21.0.2+13.1/

COPY package.json package-lock.json ./

RUN npm install

COPY nbb.edn ./

RUN npx nbb -e '(println "dependencies installed")'

COPY src/ src/

ENTRYPOINT ["npm", "start"]
```
